version: 0.1

phases:
  pre_build:
    commands:
        - echo I am into Pre-Build Phase...
        - mvn clean install
        - echo Logging into AWS ECR...
        - aws --version
        - $(aws ecr get-login --region us-east-1 --no-include-email)
        - REPOSITORY_URI=070943686835.dkr.ecr.us-east-1.amazonaws.com/keshri-registry
        - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
        - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
        
  build:
    commands:
      - echo I am into Build Phase...
      - echo Build started on `date`
      - echo Building the Docker Image...
      - docker build -t $REPOSITORY_URI:0.0.1-SNAPSHOT .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - mvn clean package
  post_build:
    commands:
      - echo I am into Post Build Phase...
      - echo Build completed on `date`
      - echo Pushing the Docker Image...
      - docker push $REPOSITORY_URI:latest .
      - echo writing image definitions file...
      - printf '[{"name":"keshri-spring-boot-aws-crud-demo","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
     
artifacts:
  files:
    - imagedefinitions.json
    - target/keshri-spring-boot-aws-crud-demo.jar
