version: 0.1

phases:
  pre_build:
    commands:
        - echo I am into Pre-Build Phase...
        - mvn clean install
        - echo Logging into AWS ECR...
        - aws --version
        - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
        - IMAGE_REPO_NAME=528578237961.dkr.ecr.us-east-1.amazonaws.com/keshri-registry
        - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo I am into Build Phase...
      - echo Build started on `date`
      - echo Building the Docker Image...
      - print
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - mvn clean package
  post_build:
    commands:
      - echo I am into Post Build Phase...
      - echo Build completed on `date`
      - echo Pushing the Docker Image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo writing image definitions file...
      - printf '[{"name":"keshri-spring-boot-aws-crud-demo","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
     
artifacts:
  files:
    - imagedefinitions.json
    - target/keshri-spring-boot-aws-crud-demo.jar
