version: 0.1

phases:
  pre_build:
    commands:
          #Abort the script at the first error
        - set -e
          #Return the exit status of the last command in the pipe that returned a non-zero return value.
        - set -o pipefail            
        - echo I am into Pre-Build Phase...
        - mvn clean install
        - echo Logging into AWS ECR...
        - aws --version
        - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
          #Abort the script at the first error
        - set -e
        - echo I am into Build Phase...
        - echo Build started on `date`
        - echo Building the Docker Image...
        - docker build -t keshri-registry:latest .
        - docker tag keshri-registry:latest 528578237961.dkr.ecr.us-east-1.amazonaws.com/keshri-registry:latest
        - mvn clean package
  post_build:
    commands:
          #Abort the script at the first error
        - set -e
        - echo I am into Post Build Phase...
        - echo Build completed on `date`
        - echo Pushing the Docker Image...
        - docker push 528578237961.dkr.ecr.us-east-1.amazonaws.com/keshri-registry:latest
        - echo writing image definitions file...
        - printf '[{"name":"keshri-spring-boot-aws-crud-demo","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
        - cat imagedefinitions.json
     
artifacts:
  files:
    - imagedefinitions.json
    - target/keshri-spring-boot-aws-crud-demo.jar
