version: 0.1

phases:
  pre_build:
    on-failure: ABORT
    commands:
        - echo I am into Pre-Build Phase...
        - mvn clean install
        - echo Logging into AWS ECR...
        - aws --version
        - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)  
  build:
    on-failure: ABORT
    commands:
        - echo I am into Build Phase...
        - echo Build started on `date`
        - echo Building the Docker Image...
        #- docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
        - docker build -t keshri-registry:latest .
        #- docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
        - docker tag keshri-registry:latest 082291235337.dkr.ecr.us-east-1.amazonaws.com/keshri-registry:latest
        
        - mvn clean package
  post_build:
    on-failure: ABORT
    commands:
        - echo I am into Post Build Phase...
        - echo Build completed on `date`
        - echo Pushing the Docker Image...
        #- docker push $REPOSITORY_URI$IMAGE_REPO_NAME:$IMAGE_TAG
        - docker push 082291235337.dkr.ecr.us-east-1.amazonaws.com/keshri-registry:latest
        - echo writing image definitions file...
        - printf '[{"name":"keshri-spring-boot-aws-crud-demo","imageUri":"%s"}]' 082291235337.dkr.ecr.us-east-1.amazonaws.com:latest > imagedefinitions.json
        - cat imagedefinitions.json
     
artifacts:
  files:
    - imagedefinitions.json
    - target/keshri-spring-boot-aws-crud-demo.jar
